/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ponderer.solitaire;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bigblackfont=0x7f020000;
        public static final int bigredfont=0x7f020001;
        public static final int bigsuits=0x7f020002;
        public static final int blackfont=0x7f020003;
        public static final int blackjack=0x7f020004;
        public static final int blackking=0x7f020005;
        public static final int blackqueen=0x7f020006;
        public static final int cardback=0x7f020007;
        public static final int medblackfont=0x7f020008;
        public static final int medredfont=0x7f020009;
        public static final int redfont=0x7f02000a;
        public static final int redjack=0x7f02000b;
        public static final int redking=0x7f02000c;
        public static final int redqueen=0x7f02000d;
        public static final int smallsuits=0x7f02000e;
        public static final int solitaire_icon=0x7f02000f;
        public static final int suits=0x7f020010;
    }
    public static final class id {
        public static final int big_cards=0x7f050004;
        public static final int button_accept=0x7f05000c;
        public static final int button_cancel=0x7f05000d;
        public static final int button_clear=0x7f050014;
        public static final int deal_1=0x7f050006;
        public static final int deal_3=0x7f050005;
        public static final int empty=0x7f050013;
        public static final int main_view=0x7f050000;
        public static final int normal_cards=0x7f050003;
        public static final int solitaire=0x7f050001;
        public static final int style_normal=0x7f050007;
        public static final int style_vegas=0x7f050008;
        public static final int suits_1=0x7f05000b;
        public static final int suits_2=0x7f05000a;
        public static final int suits_4=0x7f050009;
        public static final int text=0x7f050002;
        public static final int text_best_time=0x7f050011;
        public static final int text_high_score=0x7f050012;
        public static final int text_percentage=0x7f050010;
        public static final int text_title=0x7f05000e;
        public static final int text_wins=0x7f05000f;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int options=0x7f030001;
        public static final int stats=0x7f030002;
    }
    public static final class string {
        public static final int accept=0x7f04000d;
        public static final int app_name=0x7f040000;
        public static final int big_cards=0x7f04001c;
        public static final int cancel=0x7f04000f;
        public static final int clear=0x7f040010;
        public static final int deal_1=0x7f040012;
        public static final int deal_3=0x7f040013;
        public static final int deals_left=0x7f04001d;
        public static final int decline=0x7f04000e;
        public static final int display_options=0x7f04001a;
        public static final int help_text=0x7f04001f;
        public static final int menu_bakers=0x7f040004;
        public static final int menu_freecell=0x7f040003;
        public static final int menu_help=0x7f040009;
        public static final int menu_newgame=0x7f040005;
        public static final int menu_options=0x7f040008;
        public static final int menu_quit=0x7f04000b;
        public static final int menu_restart=0x7f040006;
        public static final int menu_save_quit=0x7f04000a;
        public static final int menu_solitaire=0x7f040001;
        public static final int menu_spider=0x7f040002;
        public static final int menu_stats=0x7f040007;
        public static final int no_deals_left=0x7f04001e;
        public static final int normal=0x7f040014;
        public static final int normal_cards=0x7f04001b;
        public static final int solitaire_layout_text_text=0x7f04000c;
        public static final int solitaire_options=0x7f040011;
        public static final int spider_options=0x7f040016;
        public static final int suits_1=0x7f040019;
        public static final int suits_2=0x7f040018;
        public static final int suits_4=0x7f040017;
        public static final int vegas=0x7f040015;
        public static final int win_text=0x7f040020;
    }
}
